apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: rag
        image: rithik933/rag:latest
        ports:
        - containerPort: 3000