apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app: rag
spec:
  type: LoadBalancer  
  selector:
    app: rag         
  ports:
  - protocol: TCP
    port: 3000        
    targetPort: 3000  
